### ISSUE TITLE
Is it possible to modify the response data?

### ISSUE THREAD

**Issue by UlyssesWu** [MindFlavor/TDSBridge#1]
Maybe it's unrelated to this project, but I'm curious and just want to ask a TDS pro like you.

Is it possible to modify the response data coming from SQL Server?

For example, I have a table contains two columns, but with the proxy I want to clear the second column data when a user queries it.

Thanks in advance.

**Comment by MindFlavor** [comment]
Theoretically you can modify the response stream any way you want. This library focuses on the *request* part of the protocol so it will not help you much I'm afraid.

That said, to change on the fly the value of fixed-length data types (int, datatime, etc...) should be relatively easy. To change the variable-length data types (varchar, etc...) will be much harder because you will have to shift the stream and repackage the header with the altered payload length.

It's interesting though, if I'll ever have the time I'll try to draft something.

**Comment by UlyssesWu** [comment]
Thank you very much 👍
